name: PHP Composer Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: (Optional) Update Composer to the latest version
    - name: Update Composer
      run: composer self-update

    # Step 3: Validate composer.json and composer.lock
    - name: Validate composer files
      run: composer validate --strict

    # Step 4: Cache Composer dependencies
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Step 5: Install dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Step 6: Verify installation and list dependencies (optional debugging)
    - name: Verify dependencies installation
      run: composer show --no-dev

    # Step 7: Run the test suite
    # Ensure you have a test script defined in your composer.json, e.g.,
    # "scripts": { "test": "vendor/bin/phpunit" }
    - name: Run test suite
      run: composer run-script test
