name: PHP Building Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List contents of the repository (for debugging)
        run: ls -la

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, mysqli

      - name: Install Composer dependencies
        run: composer install 

      - name: Validate Composer
        run: composer validate --strict
