name: CI/CD Workflow

on:
  push:
    branches:
      - main # Trigger workflow only on pushes to the main branch
  pull_request:
    branches:
      - '**' # Trigger workflow on all pull requests

jobs:
  # Job: Testing the PHP application
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Specify the PHP version
          extensions: mbstring, mysqli # PHP extensions required by your project
          coverage: none
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Step 4: Run tests
      - name: Run tests
        run: vendor/bin/phpunit --configuration phpunit.xml

  # Job: Deployment (if applicable)
  deploy:
    if: github.ref == 'refs/heads/main' # Run deploy only on main branch
    runs-on: ubuntu-latest
    needs: test # Deployment will run only after the test job is successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Add private key for SSH
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          export SSHPATH="ssh -i ssh_key -o StrictHostKeyChecking=no"
          
          # Sync files to the server
          rsync -avz --delete ./ ${REMOTE_USER}@${REMOTE_HOST}:${DEPLOY_PATH}

          # Clean up
          rm ssh_key
